name: Fly Deploy

on:
  push:
    branches:
      - main # Altere para 'master' se for o caso

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # CORREÇÃO: Usando a versão @master para garantir que é a mais recente
      - uses: superfly/fly-actions/setup-flyctl@master

      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}