name: Fly Deploy

on:
  push:
    branches:
      - main # Altere para 'master' se for o caso

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    # Define a chave de acesso para todos os passos deste job
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
    steps:
      # Passo 1: Pega o código do seu repositório
      - uses: actions/checkout@v3
      
      # Passo 2: Instala a ferramenta da Fly.io
      - uses: superfly/fly-actions/setup-flyctl@master
      
      # Passo 3: Executa o deploy (ele usará a chave de acesso do 'env' para se autenticar)
      - run: flyctl deploy --remote-only