name: Fly Deploy

on:
  push:
    branches:
      - main # Altere para 'master' se for o caso

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    env:
      FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }} # Disponibiliza o token para todo o job

    steps:
      # Passo 1: Pega o código do seu repositório
      - uses: actions/checkout@v4

      # Passo 2: Instala a ferramenta da Fly.io
      - uses: superfly/fly-actions/setup-flyctl@master

      # Passo 3 (NOVO E CRUCIAL): Realiza o login no registro Docker da Fly.io
      - name: Log in to Fly Registry
        run: echo "${{ secrets.FLY_API_TOKEN }}" | docker login registry.fly.io -u x --password-stdin

      # Passo 4: Executa o deploy, agora com a autenticação garantida
      - name: Deploy to Fly
        run: flyctl deploy --remote-only