name: Fly Deploy

on:
  push:
    branches:
      - main # Altere para 'master' se for o caso

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      # Passo 1: Pega o código do seu repositório
      - uses: actions/checkout@v3

      # Passo 2: Instala e configura a ferramenta flyctl no ambiente do robô
      - uses: superfly/fly-actions/setup-flyctl@v1

      # Passo 3: Roda o comando de deploy usando a chave secreta
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}